### ISSUE TITLE
System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by pjmagee** [BarRaider/obs-websocket-dotnet#48]
What does this mean? It only sometimes happens, not always. Running Windows 10.

```
Exception: 
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Action`1.BeginInvoke(T obj, AsyncCallback callback, Object object)
   at WebSocketSharp.WebSocket.open()
   at WebSocketSharp.WebSocket.Connect()
   at OBSWebsocketDotNet.OBSWebsocket.Connect(String url, String password)
```

**Comment by BarRaider** [comment]
Please check if still happening in v4.9.0-Beta1 release.
If it does, please reopen a new issue under "Bug Report"
