### ISSUE TITLE
[ISSUE] How to handle ExtendedSocketException?

### ISSUE THREAD

**Issue by dichternebel** [BarRaider/obs-websocket-dotnet#86]
**Issue Type** 
- Support Issue

**Describe the issue**
I am not able to catch the ExtendedSocketException when trying to connect to OBS when OBS is not started yet.

**To Reproduce**
```
            var obs = new OBSWebsocket();
            try
            {
                obs.Connect(Config.WebsocketAddress, Config.WebsocketPassword);
            }
            catch (Exception ex)
            {

            }
```

**Expected behavior**
Catch block is hit when throwing exception from the underlying WebsocketSharp.Websocket instance.

**Screenshots**
n.a.

**Versions**
OBS Version: any (doesn't matter, OBS is not started)
OBS WebSocket Version: 4.9.1
OBS WebSocket Dotnet (this library) Version: 4.9.1
OS: Windows 10

**Additional context**

WebSocket.connect|System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): 127.0.0.1:4444
                             at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
                             at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
                             at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
                             at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
                          --- End of stack trace from previous location ---
                             at System.Net.Sockets.TcpClient.Connect(String hostname, Int32 port)
                             at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
                             at WebSocketSharp.WebSocket.setClientStream()
                             at WebSocketSharp.WebSocket.doHandshake()
                             at WebSocketSharp.WebSocket.connect()

**Comment by dichternebel** [comment]
Ok, fixed that... somehow! ;-)
I didn't notice that this exception was already handled by WebSocketSharp.
The solution to my issue can be found here:
https://stackoverflow.com/questions/68554560/websocketsharp-cannot-catch-exceptions

It just disables the logging output and: silence! ^^
